sity = [
    [
        "Abay",
        "Akkol",
        "Aksay",
        "Aksu",
        "Aktau",
        "Aktobe",
        "Alga",
        "Almaty",
        "Aralsk",
        "Arkalyk",
        "Arys",
        "Atbasar",
        "Atyrau",
        "Ayagoz"
    ],
    [
        "Baikonur ",
        "Balkhash",
        "Bulayevo"
    ],
    [
        "Derzhavinsk"
    ],
    [
        "Ereymentau",
        "Esik",
        "Esil",
        "Ekibastuz",
        "Emba"
    ],
    [
        "Zhanaozen",
        "Zhanatas",
        "Zharkent",
        "Zhezkazgan",
        "Zhem",
        "Zhetisay",
        "Zhetikara"
    ],
    [
        "Zaisan",
        "Zyryanovsk"
    ],
    [
        "Kazalinsk",
        "Kandyagash",
        "Kapshagai",
        "Karaganda",
        "Karazhal",
        "Karatau",
        "Karkaralinsk",
        "Kentau",
        "Kokshetau",
        "Kostanay",
        "Kurchatov",
        "Kurchatov",
        "Khromtau"
    ],
    [
        "Lenger",
        "Lisakovsk"
    ],
    [
        "Makinsk",
        "Mamlyutka"
    ],
    [
        "Нур-Султан"
    ],
    [
        "Pavlodar",
        "Petropavlovsk",
        "Priozersk"
    ],
    [
        "Ridder",
        "Rudny"
    ],
    [
        "Saran",
        "Sarkand",
        "Saryagash",
        "Satpayev",
        "Semey",
        "Sergeyevka",
        "Serebryansk",
        "Stepnogorsk",
        "Stepnyak"
    ],
    [
        "Taiynsha",
        "Talgar",
        "Taldykorgan",
        "Taraz",
        "Tekeli",
        "Temir",
        "Temirtau",
        "Turkestan"
    ],
    [
        "Uralsk",
        "Ust-Kamenogorsk",
        "Usharal",
        "Ushtobe"
    ],
    [
        "Charsk"
    ],
    [
        "Shalkar",
        "Shardara",
        "Shakhtinsk",
        "Shemonaikha",
        "Shu",
        "Shymkent",
        "Shchuchinsk"
    ],
]
bark = ["Назад"]